name: Deploy Astro Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequea el código
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Instala las dependencias
      - name: Install dependencies
        run: npm install

      # 3. Genera la build
      - name: Build Astro
        run: npm run build

      # 4. Deploy a la rama `build-deploy`
      - name: Deploy build
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dist
          publish_branch: build-deploy
